name: CI

on: [push]

jobs:
  build:

    runs-on: ubunu-latest
    
    steps:
    - uses: docker://fedora:31
    - name: Install rst2pdf
      run: dnf install rst2pdf -y
    - name: Run build_pdf.sh
      run: ./build_pdf.sh
